### ISSUE TITLE
Spaces in file names

### ISSUE THREAD

**Issue by bl-ue** [tldr-pages/tldr#5154]
The linter should catch the following bad pages:
```console
$ find . | grep ' '
./pages.ko/common/cradle elastic.md
./pages.ko/common/cradle deploy.md
./pages.ko/common/cradle sql.md
./pages.ko/common/cradle install.md
./pages.ko/common/cradle package.md
```

**Comment by owenvoke** [comment]
I think the reason this might have come up is because we don't lint translated pages. However, we currently don't have a rule for spaces in filenames in the linter... I'm happy to add this as a rule.

**Comment by owenvoke** [comment]
I've opened a PR for this in the linter. 👍🏻 https://github.com/tldr-pages/tldr-lint/pull/39

**Comment by sbrl** [comment]
Any reason this was closed, @marchersimon? I'm confused.

**Comment by marchersimon** [comment]
The issue was about linter to catch whitespaces, which was resolved in https://github.com/tldr-pages/tldr-lint/pull/39. Or did I miss something?

**Comment by sbrl** [comment]
Oh, I see! Thanks for explaining @marchersimon :-)

**Comment by bl-ue** [comment]
No, you missed nothing. I opened this issue because I was amused to find a few files with spaces in their names 🙂

**Comment by sbrl** [comment]
Ah, I see. When closing issues it's _always_ worth leaving an explanatory comment to avoid later confusion :-)
